### ISSUE TITLE
How to unit test a promise?

### ISSUE THREAD

**Issue by gmansilla** [guzzle/promises#26] opened 2016-04-27 13:13 UTC
Disclaimer: This is not a bug, this is just a question.

I have created a web client for a particular API. I also created a Middleware for handling exceptions, the code looks like this:

    class ErrorHandlerMiddleware {
        public static function create() {
            return function (callable $handler) {
                return function ($request, array $options) use ($handler) {
                    if ($options['http_errors']) {
                        return $handler($request, $options);
                    }

                    return $handler($request, $options)->then(
                        function (ResponseInterface $response) use ($request, $handler) {
                            $code = $response->getStatusCode();
                            if ($code < 400) {
                                return $response;
                            }

                            switch ($code) {
                                // ....
                                case '401':
                                    throw new AccessDeniedException('Access Denied', $request, $response);
                                //...
                            }

                        },
                        function (RequestException $e) use ($request, $handler) {
                            throw new ConnectException('Service not working', $request);
                        }
                    );
                };
            };
        }
    }

My testing strategy is to create a dummy response object and set the status code to say 401 and then assert that an AccessDeniedException is thrown.

This is what I've done in my unit test

    public function testFoo() {
        $options = [
            'http_errors' => false
        ];
        $request = new \GuzzleHttp\Psr7\Request('get', 'http://foo.com');
        $handler = function($request, $options) {
            return new GuzzleHttp\Promise\Promise();
        };

        $middleware = ErrorHandlerMiddleware::create();
        $request_processor = $middleware($handler);

        $promise = $request_processor($request, $options);
    }

According to the [documentation](https://github.com/guzzle/promises#resolving-a-promise) I need to "resolve" the promise so that I get my callback.

Question 1: How do I use my dummy $response object with the callback defined in the promise?

I tried something like this

    $resolved = $promise->resolve('return new \GuzzleHttp\Psr7\Response(200)');
    var_dump($resolved());

But I get this error message: "Function name must be a string"

Question 2: It seems like "resolve" only accepts strings, if that's the case, How Am I supposed to use my $response object inside the promise?

**Comment by jeskew** [comment] 2016-04-29 18:13
You can resolve the promise with a response object. Alternatively, you can return a [`FulfilledPromse`](https://github.com/guzzle/promises/blob/master/src/FulfilledPromise.php), which will already be resolved with whatever value you pass to its constructor.

**Closed by jeskew** 2016-04-29 18:13 UTC

**Comment by gmansilla** [comment] 2016-04-29 20:01
@jeskew thanks for your response.

When I try to resolve the Promise with a Response Object I get the message "Function name must be a string"

**Comment by jeskew** [comment] 2016-04-29 21:36
I believe that error is being thrown by something unrelated. PHP provides that error message when you try to invoke something that isn't callable as a function, such as in the following example:
```php
$a = 1;
$a();
```

There are examples of promises being resolved with objects in this repository's unit test suite. See https://github.com/guzzle/promises/blob/master/tests/PromiseTest.php#L577 for an example of how this is done.

**Comment by bpawan** [comment] 2018-11-09 07:11
Might be a related problem. I have the following problem posted on the stackoverflow, that I encountered while unit testing the class which takes guzzle client as dependency along with the handlers for the response. The problem is when I send an async request and recieve the promise and do something with the response. I could not find a way to test the handling of the response since the logic is inside the callback.

Here is the link to the problem: https://stackoverflow.com/questions/53211474/unit-testing-guzzle-http-promises-callbacks

I am not sure if this is related to guzzle promise or in general testing of the callbacks in php.

Any suggestions here?
